// src/App.tsx
import styles from "./App.module.scss";
import { About, Contact, Hero, Projects, Skills } from "./components/sections";
import "./styles/App.scss";

export default function App() {
  return (
    <div className={styles.App}>
      <Hero />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
}

// src/App.svelte
<script lang="ts">
  import Hero from './lib/Sections/Hero/Hero.svelte';
  import TopBar from './lib/TopBar/TopBar.svelte';
  import Skills from './lib/Sections/Skills/Skills.svelte';
  import Contact from './lib/Sections/Contact/Contact.svelte';
</script>

<main class="page-main">
  <TopBar />
  <Hero />
  <Skills />
  <Contact />
</main>
